io:
  dataname: shanghaiTech  # york, shanghaiTech
  resume_from:  # ckpt path when the program was stopped by accident
  model_initialize_file:


model:
  # backbone parameters
  backbone: stacked_hourglass  # stacked_hourglass, hourglass_lines
  depth: 2
  num_stacks: 1
  num_blocks: 1
  inplanes: 64

